# File: wrangler.toml

name = "m"
main = "worker.js"
compatibility_date = "2023-12-01"


[site]
bucket = "./public"





[[migrations]]
tag = "your-unique-migration-tag" # Use a unique tag, e.g., "v3", "tokenlocker-delete-v1"
deleted_classes = ["TokenLocker"]