# File: wrangler.toml

name = "m"
main = "src/index.js"
compatibility_date = "2023-12-01"


[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "CLAIM_LOCK_DO" # Nama yang akan kita gunakan di kode: c.env.CLAIM_LOCK_DO
class_name = "ClaimLockDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClaimLockDO"]