# File: wrangler.toml

name = "m"
main = "src/index.js"
compatibility_date = "2023-12-01"


[assets]
directory = "./static"
binding = "ASSETS"

[[kv_namespaces]]
binding = "ADMIN"
id = "65af14e6ce5f4aad928fc3e474c8642e"

[[d1_databases]]
binding = "DB" # Nama variabel yang akan digunakan di kode Worker
database_name = "tokens"
database_id = "0c98dba8-35ca-4ba4-a7ae-6fd5617985f4"

[[durable_objects.bindings]]
name = "WEBSOCKET_DO" # Nama ini harus sama dengan yang digunakan di index.js (c.env.WEBSOCKET_DO)
class_name = "WebSocketDO" # Nama kelas yang diekspor dari file .do.js

# ---> TAMBAHKAN DUA BARIS DI BAWAH INI <---
[[durable_objects.bindings]]
name = "SIMPLE_WEBRTC_DO"
class_name = "SimpleWebRTC_DO"


# TAMBAHKAN BAGIAN INI
[[migrations]]
tag = "v2" # Anda bisa menamainya apa saja
new_sqlite_classes = [ "SimpleWebRTC_DO" ]