# Nama proyek Worker Anda
name = "m" # Beri nama baru agar tidak konflik

# Titik masuk utama untuk kode Worker Anda
main = "src/index.js"

# Tanggal kompatibilitas
compatibility_date = "2024-03-20"

# --- BAGIAN KUNCI UNTUK ASET STATIS ---
# Memberitahu Worker untuk menyajikan file dari direktori "public"
[site]
bucket = "./public"

# Binding KV Anda (tetap sama)
[[kv_namespaces]]
binding = "TOKEN"
id = "e4b68d7dd477413fbe140f59259254c7"

[[kv_namespaces]]
binding = "ADMIN"
id = "65af14e6ce5f4aad928fc3e474c8642e"

# Binding Durable Object Anda (jika Anda menambahkannya)
# [[durable_objects.bindings]]
# name = "COUNTER_DO"
# class_name = "Counter"