# Nama proyek Anda di Cloudflare
name = "m"

# Memberitahu Cloudflare Pages bahwa file statis (HTML, CSS, JS) ada di direktori root.
pages_build_output_dir = "."

# BARIS BARU: Menentukan file Worker utama. Ini adalah inti dari migrasi.
main = "_worker.js"

# Tanggal kompatibilitas untuk memastikan API berfungsi seperti yang diharapkan
compatibility_date = "2024-03-20"
#compatibility_flags = ["nodejs_compat"]

# Konfigurasi binding ke KV Namespace Anda (Sudah benar)
[[kv_namespaces]]
binding = "TOKEN" # Nama variabel yang akan digunakan di dalam Functions
id = "e4b68d7dd477413fbe140f59259254c7" # ID KV Namespace Anda

[[kv_namespaces]]
binding = "ADMIN"
id = "65af14e6ce5f4aad928fc3e474c8642e"